# investment_risk_analysis_clean.R
install.packages(c("tidyverse","WDI","slider","fixest","modelsummary","ggplot2","ggrepel"))
library(tidyverse); library(WDI); library(slider); library(fixest); library(modelsummary); library(ggplot2); library(ggrepel)
wb_raw <- read_csv(file.choose(), show_col_types = FALSE)
wb1 <- wb_raw %>% rename(country = `Country Name`, iso3 = `Country Code`, series_name = `Series Name`, series_code = `Series Code`)
wb_long <- wb1 %>% pivot_longer(cols = starts_with("19") | starts_with("20"), names_to = "year", values_to = "value")
wb_long2 <- wb_long %>% mutate(year = as.integer(str_extract(year, "^\\d{4}")), value = as.numeric(value))
wb_main <- wb_long2 %>% filter(series_code %in% c("BX.KLT.DINV.CD.WD", "SP.POP.TOTL", "PA.NUS.FCRF", "FP.CPI.TOTL.ZG", "NY.GDP.PCAP.KD"))
wb_wide <- wb_main %>% mutate(var = recode(series_code, "BX.KLT.DINV.CD.WD" = "fdi", "FP.CPI.TOTL.ZG" = "inflation", "PA.NUS.FCRF" = "exrate", "SP.POP.TOTL" = "population", "NY.GDP.PCAP.KD" = "gdp_pc")) %>% select(country, iso3, year, var, value) %>% pivot_wider(names_from = var, values_from = value) %>% arrange(iso3, year)
trade_data <- WDI(country = "all", indicator = c("exports" = "NE.EXP.GNFS.ZS", "imports" = "NE.IMP.GNFS.ZS"), start = 1980, end = 2022)
trade_data <- trade_data %>% select(iso3 = iso3c, year, exports, imports) %>% mutate(trade_open = exports + imports)
wb_model <- wb_wide %>% left_join(trade_data, by = c("iso3", "year")) %>% arrange(iso3, year) %>% group_by(iso3) %>% mutate(fdi_pc = fdi / population, log_fdi_pc = log(fdi_pc + 1), log_gdp_pc = log(gdp_pc), exrate_change = log(exrate) - log(lag(exrate)), abs_exrate_change = abs(exrate_change), inflation_change = inflation - lag(inflation), abs_inflation_change = abs(inflation_change), exrate_range5 = slide_dbl(exrate, ~max(.x) - min(.x), .before = 4, .complete = TRUE), inflation_range5 = slide_dbl(inflation, ~max(.x) - min(.x), .before = 4, .complete = TRUE), exrate_sd5 = slide_dbl(exrate, sd, .before = 4, .complete = TRUE), inflation_sd5 = slide_dbl(inflation, sd, .before = 4, .complete = TRUE)) %>% ungroup()
baseline_model <- feols(log_fdi_pc ~ abs_exrate_change + abs_inflation_change + trade_open + log_gdp_pc | iso3 + year, data = wb_model, cluster = ~iso3)
range_volatility_model <- feols(log_fdi_pc ~ exrate_range5 + inflation_range5 + trade_open + log_gdp_pc | iso3 + year, data = wb_model, cluster = ~iso3)
sd_volatility_model <- feols(log_fdi_pc ~ exrate_sd5 + inflation_sd5 + trade_open + log_gdp_pc | iso3 + year, data = wb_model, cluster = ~iso3)
modelsummary(list("Baseline Abs Change" = baseline_model, "Range Volatility" = range_volatility_model, "SD Volatility" = sd_volatility_model), stars = TRUE, output = "robustness_volatility_results.html")
wb_model_no_outliers <- wb_model %>% filter(!iso3 %in% c("ZWE", "COD"))
graph_exrate_final <- wb_model_no_outliers %>% group_by(iso3) %>% summarise(avg_fdi = mean(fdi_pc, na.rm = TRUE), avg_volatility = mean(abs_exrate_change, na.rm = TRUE)) %>% ggplot(aes(x = avg_volatility, y = avg_fdi, label = iso3)) + geom_point() + geom_text_repel(size = 3) + geom_smooth(method = "lm", se = FALSE) + labs(x = "Exchange Rate Volatility (Absolute Change)", y = "FDI per capita (current US$)", title = "Exchange Rate Volatility and FDI per capita") + theme_minimal()
print(graph_exrate_final)
ggsave("graph_exrate_final.png", plot = graph_exrate_final, width = 10, height = 7, dpi = 300)
graph_inflation_final <- wb_model_no_outliers %>% group_by(iso3) %>% summarise(avg_fdi = mean(fdi_pc, na.rm = TRUE), avg_volatility = mean(abs_inflation_change, na.rm = TRUE)) %>% ggplot(aes(x = avg_volatility, y = avg_fdi, label = iso3)) + geom_point() + geom_text_repel(size = 3) + geom_smooth(method = "lm", se = FALSE) + labs(x = "Inflation Volatility (Absolute Change)", y = "FDI per capita (current US$)", title = "Inflation Volatility and FDI per capita") + theme_minimal()
print(graph_inflation_final)
ggsave("graph_inflation_final.png", plot = graph_inflation_final, width = 10, height = 7, dpi = 300)
modelsummary(list("Baseline Model" = baseline_model), stars = TRUE, output = "baseline_model_results.html")
